#!/home/pipeline-stable/.conda/envs/pipeline/bin/python

from pipeline.services.scheduler import Scheduler
from pipeline.services.database import ProcessStatus

import argparse

"""ln -s /home/pipeline-stable/pipeline/pipeline/cli/autostash /usr/local/bin/autostash"""

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Autostash failed scheduler entries")
    parser.add_argument(
        "--whitelist-error",
        "-e",
        type=int,
        nargs="*",
        default=[382],  # [230],
        help="List of error codes to whitelist (default: 230). Usage: -e 230 382",
    )
    parser.add_argument(
        "--whitelist-obj",
        type=str,
        nargs="*",
        default=[],
        help="List of objects to whitelist (default: [])",
    )
    parser.add_argument(
        "--blacklist-object",
        type=str,
        nargs="*",
        default=["UDS"],
        help="List of objects to blacklist (default: ['UDS'])",
    )

    args = parser.parse_args()
    whitelist_error = args.whitelist_error
    whitelist_obj = args.whitelist_obj
    blacklist_object = args.blacklist_object

    print(
        f"Autostashing failed tasks (whitelist_error={whitelist_error}, whitelist_obj={whitelist_obj}, blacklist_object={blacklist_object})"
    )

    sc = Scheduler()

    names = sc._get_failed_tasks_from_db()

    tab = ProcessStatus().export_to_table()

    # Match failed scheduler tasks
    failed_mask = tab["name"].isin(names[:, 1])

    # Whitelist: error in list OR object in list
    error_match = tab["errors"].isin(whitelist_error)
    obj_match = tab["object"].isin(whitelist_obj)
    whitelist_match = error_match | obj_match

    # Blacklist: exclude these objects
    not_blacklisted = ~tab["object"].isin(blacklist_object)

    to_stash = tab[failed_mask & whitelist_match & not_blacklisted]["name"]

    failed_to_stashed_idx = [int(names[:, 0][names[:, 1] == fp][0]) for fp in to_stash]

    for idx in failed_to_stashed_idx:
        sc._stash_task_from_db(idx)
