#!/home/pipeline-stable/.conda/envs/pipeline/bin/python

import argparse
import sys
import signal

from pipeline.const.run import DEFAULT_SCIDATA_PROCESSES
from pipeline.run import run_scidata_reduction

# from pipeline.errors import AstrometryError, SinglePhotometryError, CoaddError
from pipeline.errors import EmptyInputAfterSanityRejectionError


def signal_handler(sig, frame):
    print("\nTerminate process")
    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Reduce astronomical FITS images by performing astrometry, photometry, "
            "image stacking, and image subtraction. Supports various processing steps "
            "and optional overwrite functionality."
        )
    )
    parser.add_argument("-config", type=str, required=True, help="Path to the preprocessing configuration file")
    parser.add_argument(
        "-processes",
        nargs="*",
        required=False,
        help="Processes to run (default: all). Pass -processes with no args to skip all.",
    )
    parser.add_argument("-overwrite", action="store_true", help="Overwrite existing results")
    parser.add_argument("-is_too", action="store_true", help="Use TOO processing")
    args = parser.parse_args()

    # if None, default behavior; if [], skips sciprocess
    if args.processes is None:
        args.processes = DEFAULT_SCIDATA_PROCESSES

    if not args.config.endswith(".yml"):
        print(f"\nError: {args.config} is not a valid configuration file")
        sys.exit(1)

    try:
        run_scidata_reduction(args.config, processes=args.processes, overwrite=args.overwrite, is_too=args.is_too)

    # Empty inputs due to AstrometryError.EarlyQARejectionError is a normal pipeline procedure
    # Mostly at SinglePhotometry and Coadd
    except EmptyInputAfterSanityRejectionError as e:
        print(f"\nError: {e}")
        sys.exit(0)

    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)
