#!/home/pipeline-stable/.conda/envs/pipeline/bin/python

import argparse
import sys
import signal

from pipeline.wrapper import DataReduction


def signal_handler(sig, frame):
    print("\nTerminate process")
    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Run data reduction for a given date",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("condition", type=str, help="Condition to run data reduction for")
    parser.add_argument(
        "--priority",
        type=int,
        default=4,
        help="Base priority for scheduled jobs (default: 10)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite all outputs (preprocess and science)",
    )
    parser.add_argument(
        "--overwrite-config",
        action="store_true",
        help="Overwrite configs",
    )
    parser.add_argument(
        "--overwrite-data",
        action="store_true",
        help="Overwrite pipeline data outputs (same as --overwrite for from_list)",
    )
    parser.add_argument(
        "--overwrite-preprocess",
        action="store_true",
        help="Overwrite preprocess outputs only",
    )
    parser.add_argument(
        "--overwrite-science",
        action="store_true",
        help="Overwrite science outputs only",
    )
    parser.add_argument(
        "--overwrite-schedule",
        action="store_true",
        help="Overwrite existing schedule in the database",
    )

    args = parser.parse_args()

    if args.condition is None:
        print("Error: Condition is required")
        sys.exit(1)

    args.condition = args.condition.split(",")
    try:
        dr = DataReduction(args.condition, use_db=True, is_pipeline=True)
        dr.run(
            use_system_queue=True,
            base_priority=args.priority,
            overwrite=args.overwrite,
            overwrite_config=args.overwrite or args.overwrite_config,
            overwrite_data=args.overwrite or args.overwrite_data,
            overwrite_preprocess=args.overwrite or args.overwrite_data or args.overwrite_preprocess,
            overwrite_science=args.overwrite or args.overwrite_data or args.overwrite_science,
            overwrite_schedule=args.overwrite_schedule,
        )
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)
