name: 

info:
  version: '2.0'  # legacy gppy-gpu is 1.0
  project: 7DT/7DS
  creation_datetime:
  last_update_datetime:

settings:
  ToO: False
  obsmode:  # Deep Spec Color Search Single
  header_pad: 5  # assuming final header is 5 * 2880 bytes long. 6 to include polygon info
  local_astref: 
  combine:
  gpu_enabled: True
  verbose_gpu: True  # use logger later

obs:
  # OBS Info should be updated from header
  pixscale: 0.505  # arcsec/pix
  n_binning: 
  gain: 
  unit: 
  camera: 
  filter:
  object:
  date:  # date of datetime - 12h. dirname of obsdata
  datetime:  # UTC
  ra:
  dec:
  exposure:
  
file: 
  raw_files: 
  processed_files: 
  # stacked_file:
  # weight_file:

preprocess:
  masterframe: default # closest, custom
  mbias_link: # master_frame/2001-02-23_1x1_gain2750/7DT11/link_20250102_C3.bias
  mdark_link: # master_frame/2001-02-23_1x1_gain2750/7DT11/link_20250102_100_C3.dark
  mflat_link: # master_frame/2001-02-23_1x1_gain2750/7DT11/link_20250102_m625_C3.flat

  mbias_file: # master_frame/2001-02-23_1x1_gain2750/7DT11/bias_20250102_C3.fits
  mdark_file: # master_frame/2001-02-23_1x1_gain2750/7DT11/dark_20250102_100s_C3.fits
  mflat_file: # master_frame/2001-02-23_1x1_gain2750/7DT11/flat_20250102_m625_C3.fits
  bpmask_file:

astrometry:
  path:
    ref_ris_dir: "/lyman/data1/factory/catalog/gaia_dr3_7DT"
    ref_query_dir: "/lyman/data1/factory/ref_scamp"
  ahead_file: "/data/pipeline_reform/dhhyun_lab/scamptest/ahead/calib_7DT11_T07304_20250115_050155_g_60_nocrval.ahead"

photometry:
  # path:  # if user-input
  #   - file1
  #   - file2
  path:
    ref_ris_dir: "/lyman/data1/factory/ref_cat"  # divided by RIS tiles
    ref_gaia_dir: "/lyman/data1/Calibration/7DT-Calibration/output/Calibration_Tile"  # divided by Gaia team
  match_radius: 1.0
  photfraction: 0.75
  refcatname: GaiaXP
  refqueryradius: 0.9
  ref_mag_lower: 12
  ref_mag_upper: 17.5
  ref_mag_err_upper: 0.05
  flagcut: 0
  check: False
  satur_margin: 0.99  # factor multiplied to the propagated hardware upper limit
  sex_vars:
    DETECT_MINAREA: 5
    DETECT_THRESH: 3.0
    DEBLEND_NTHRESH: 64
    DEBLEND_MINCONT: 0.0001
    BACK_SIZE: 64
    BACK_FILTERSIZE: 3
    BACKPHOTO_TYPE: LOCAL

imstack:
  path:
    ref_image_dir: "/lyman/data1/factory/ref_frame"
  gpu: True
  zp_key: 'ZP_AUTO'
  # images_to_combine:
  bkgsub_type: 'Dynamic'
  weight_map: true
  joint_wcs: False
  interp_type: 'median'
  convolve: 'Gaussian'
  propagate_mask: False

imsubtract:
  refim_file:
  input_mask:
  template_mask:

logging:
  level: INFO
  file: 
  format: '[%(levelname)s] %(asctime)s - %(name)s - %(message)s'
  handlers:
    - console
    - file

flag:
  configuration: false
  preprocess: false
  astrometry: false
  single_photometry: false
  combine: false
  # combined_astrometry: false
  combined_photometry: false
  subtraction: false